name: Build Wallet

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

defaults:
 run:
  working-directory: /tmp/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: absolutapps/oracle-12c-ee
      options: --user root
 ##    image: gvenzl/oracle-xe:21-full

    steps:
      - name: Create new wallet
        run:  orapki wallet create -wallet /tmp/public_wallet -auto_login_only
      - name: Download Amazon bundle
        run: pwd && curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o global-bundle.pem
      - name: List files
        run: ls -lah
      - name: Extract certs from Amazon global bundle and add those to the wallet
        run: |
           csplit global-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' && rm xx00
           ls -lah
           for f in $(ls -1 xx*); do echo $f && orapki wallet add -wallet /tmp/public_wallet -trusted_cert -cert $f -auto_login_only; done    
           rm xx*
      - name: Extract certs from Mozilla CA bundle and add those to the wallet
        run: |
           csplit /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' && rm xx00
           ls -lah
           for f in $(ls -1 xx*); do echo $f && orapki wallet add -wallet /tmp/public_wallet -trusted_cert -cert $f -auto_login_only; done    
           rm xx*
      - uses: actions/upload-artifact@v4
        with:
          name: wallet
          path: /tmp/public_wallet
