name: Build Oracle Wallet with Public CA Certificates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:
  #schedule:
    # Rebuild monthly to get updated certificates
    #- cron: '0 2 1 * *'

env:
  WALLET_DIR: /tmp/public_wallet
  CERT_DIR: /tmp/certs

defaults:
  run:
    working-directory: /tmp/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gvenzl/oracle-xe:18-slim
      options: --user root
    
    permissions:
      contents: read
      actions: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup working directories
        run: |
          # Ensure proper permissions for GitHub Actions
          echo "Current user: $(whoami)"
          echo "Current umask: $(umask)"
          echo "Available commands:"
          which ls chmod mkdir cp rm curl grep head cat || echo "Some basic commands missing"
          echo "Available in /bin:"
          ls /bin/ | head -10 || echo "Cannot list /bin"
          echo "Available in /usr/bin:"
          ls /usr/bin/ | head -10 || echo "Cannot list /usr/bin"
          
          echo "GitHub workspace permissions:"
          ls -la $GITHUB_WORKSPACE/ || echo "No access to workspace"
          
          umask 022
          mkdir -p ${{ env.WALLET_DIR }} ${{ env.CERT_DIR }}
          chmod 755 ${{ env.WALLET_DIR }} ${{ env.CERT_DIR }}
          ls -la /tmp/
          
      - name: Create new Oracle wallet
        run: |
          echo "Creating Oracle wallet at ${{ env.WALLET_DIR }}"
          echo "Oracle version info:"
          orapki help 2>&1 | head -5 || echo "orapki help failed"
          echo "Oracle environment:"
          echo "ORACLE_HOME: $ORACLE_HOME"
          echo "TNS_ADMIN: $TNS_ADMIN"
          
          if orapki wallet create -wallet ${{ env.WALLET_DIR }} -auto_login_only; then
            echo "Wallet created successfully"
            ls -la ${{ env.WALLET_DIR }}
          else
            echo "ERROR: Failed to create wallet"
            echo "Checking Oracle environment..."
            which orapki || echo "orapki not found in PATH"
            echo "PATH: $PATH"
            echo "Oracle environment variables:"
            env | grep -i oracle || echo "No Oracle environment variables"
            exit 1
          fi
          
      - name: Download certificate bundles
        run: |
          echo "Downloading Amazon RDS global bundle..."
          if curl -fsSL https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o ${{ env.CERT_DIR }}/amazon-global-bundle.pem; then
            echo "✅ Amazon global bundle downloaded"
          else
            echo "❌ Failed to download Amazon global bundle"
            exit 1
          fi
          
          echo "Downloading Amazon RDS regional bundles..."
          curl -fsSL https://truststore.pki.rds.amazonaws.com/us-east-1/us-east-1-bundle.pem -o ${{ env.CERT_DIR }}/amazon-us-east-1-bundle.pem || echo "⚠️ Failed to download us-east-1 bundle"
          curl -fsSL https://truststore.pki.rds.amazonaws.com/us-west-2/us-west-2-bundle.pem -o ${{ env.CERT_DIR }}/amazon-us-west-2-bundle.pem || echo "⚠️ Failed to download us-west-2 bundle"
          curl -fsSL https://truststore.pki.rds.amazonaws.com/eu-west-1/eu-west-1-bundle.pem -o ${{ env.CERT_DIR }}/amazon-eu-west-1-bundle.pem || echo "⚠️ Failed to download eu-west-1 bundle"
          
          echo "Copying Mozilla CA bundle..."
          if [ -f "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem" ]; then
            cp /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem ${{ env.CERT_DIR }}/mozilla-ca-bundle.pem
            echo "✅ Mozilla CA bundle copied"
          elif [ -f "/etc/ssl/certs/ca-certificates.crt" ]; then
            cp /etc/ssl/certs/ca-certificates.crt ${{ env.CERT_DIR }}/mozilla-ca-bundle.pem
            echo "✅ CA certificates copied from /etc/ssl/certs/"
          elif [ -f "/etc/ssl/certs/ca-bundle.crt" ]; then
            cp /etc/ssl/certs/ca-bundle.crt ${{ env.CERT_DIR }}/mozilla-ca-bundle.pem
            echo "✅ CA certificates copied from /etc/ssl/certs/ca-bundle.crt"
          else
            echo "❌ No CA bundle found at expected locations"
            echo "Searching for CA bundles..."
            ls /etc/ssl/certs/ 2>/dev/null | head -10 || echo "Cannot list /etc/ssl/certs/"
            ls /etc/pki/ 2>/dev/null | head -10 || echo "Cannot list /etc/pki/"
            exit 1
          fi
          
          echo "Downloaded certificate bundles:"
          ls -la ${{ env.CERT_DIR }}
          echo "File sizes:"
          ls -lh ${{ env.CERT_DIR }}/* || echo "Cannot show file sizes"
          
      - name: Validate certificate bundles
        run: |
          echo "Validating certificate bundles..."
          for bundle in ${{ env.CERT_DIR }}/*.pem; do
            echo "Validating $(basename $bundle)..."
            if ! grep -q "BEGIN CERTIFICATE" "$bundle"; then
              echo "ERROR: No certificates found in $bundle"
              exit 1
            fi
            cert_count=$(grep -c "BEGIN CERTIFICATE" "$bundle")
            echo "  Found $cert_count certificates"
          done
          
      - name: Process Amazon global bundle certificates
        run: |
          echo "Processing Amazon global bundle..."
          cd ${{ env.CERT_DIR }}
          
          if [ ! -f "amazon-global-bundle.pem" ]; then
            echo "ERROR: Amazon global bundle not found"
            exit 1
          fi
          
          # Split certificates with error handling
          if csplit amazon-global-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' --prefix=amazon-global- --suffix-format='%03d.pem' --quiet; then
            echo "Successfully split Amazon global bundle"
          else
            echo "ERROR: Failed to split Amazon global bundle"
            echo "Bundle content preview:"
            head -10 amazon-global-bundle.pem
            exit 1
          fi
          
          rm amazon-global-000.pem 2>/dev/null || true
          
          cert_count=0
          failed_count=0
          duplicate_count=0
          for cert in amazon-global-*.pem; do
            if [ -f "$cert" ] && [ -s "$cert" ]; then
              echo "Adding Amazon global certificate: $cert"
              # Capture orapki output to check for specific errors
              if orapki_output=$(orapki wallet add -wallet ${{ env.WALLET_DIR }} -trusted_cert -cert "$cert" -auto_login_only 2>&1); then
                cert_count=$((cert_count + 1))
                echo "✅ Successfully added certificate $cert"
              else
                if echo "$orapki_output" | grep -q "PKI-04003.*already present"; then
                  duplicate_count=$((duplicate_count + 1))
                  echo "ℹ️ Certificate $cert already exists (skipping)"
                else
                  failed_count=$((failed_count + 1))
                  echo "⚠️ WARNING: Failed to add certificate $cert"
                  echo "Error: $orapki_output"
                fi
              fi
            fi
          done
          echo "Successfully added $cert_count new Amazon global certificates"
          if [ $duplicate_count -gt 0 ]; then
            echo "Skipped $duplicate_count duplicate certificates"
          fi
          if [ $failed_count -gt 0 ]; then
            echo "Failed to add $failed_count certificates"
          fi
          rm amazon-global-*.pem
          
          # Ensure we have at least some certificates (counting new + duplicates as success)
          total_processed=$((cert_count + duplicate_count))
          if [ $total_processed -eq 0 ]; then
            echo "ERROR: No Amazon global certificates were processed successfully"
            exit 1
          fi
          
      - name: Process Amazon regional bundle certificates
        continue-on-error: true
        run: |
          echo "Processing Amazon regional bundles..."
          cd ${{ env.CERT_DIR }}
          
          total_regional_certs=0
          for bundle in amazon-us-east-1-bundle.pem amazon-us-west-2-bundle.pem amazon-eu-west-1-bundle.pem; do
            if [ -f "$bundle" ]; then
              region=$(echo $bundle | sed 's/amazon-\(.*\)-bundle.pem/\1/')
              echo "Processing $region certificates..."
              
              # Check if bundle has certificates
              if ! grep -q "BEGIN CERTIFICATE" "$bundle"; then
                echo "WARNING: No certificates found in $bundle, skipping"
                continue
              fi
              
              if csplit "$bundle" '/-----BEGIN CERTIFICATE-----/' '{*}' --prefix="amazon-${region}-" --suffix-format='%03d.pem' --quiet; then
                rm "amazon-${region}-000.pem" 2>/dev/null || true
                
                cert_count=0
                for cert in amazon-${region}-*.pem; do
                  if [ -f "$cert" ] && [ -s "$cert" ]; then
                    if orapki wallet add -wallet ${{ env.WALLET_DIR }} -trusted_cert -cert "$cert" -auto_login_only; then
                      cert_count=$((cert_count + 1))
                    fi
                  fi
                done
                echo "Successfully added $cert_count certificates from $region"
                total_regional_certs=$((total_regional_certs + cert_count))
                rm amazon-${region}-*.pem 2>/dev/null || true
              else
                echo "WARNING: Failed to split $bundle"
              fi
            else
              echo "WARNING: Bundle $bundle not found, skipping"
            fi
          done
          echo "Total regional certificates added: $total_regional_certs"
          
      - name: Process Mozilla CA bundle certificates
        run: |
          echo "Processing Mozilla CA bundle..."
          cd ${{ env.CERT_DIR }}
          
          if [ ! -f "mozilla-ca-bundle.pem" ]; then
            echo "ERROR: Mozilla CA bundle not found"
            exit 1
          fi
          
          # Check bundle content first
          cert_count_in_bundle=$(grep -c "BEGIN CERTIFICATE" mozilla-ca-bundle.pem)
          echo "Found $cert_count_in_bundle certificates in Mozilla bundle"
          
          # Split certificates with error handling
          if csplit mozilla-ca-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' --prefix=mozilla- --suffix-format='%03d.pem' --quiet; then
            echo "Successfully split Mozilla CA bundle"
          else
            echo "ERROR: Failed to split Mozilla CA bundle"
            echo "Bundle content preview:"
            head -10 mozilla-ca-bundle.pem
            exit 1
          fi
          
          rm mozilla-000.pem 2>/dev/null || true
          
          cert_count=0
          failed_count=0
          duplicate_count=0
          for cert in mozilla-*.pem; do
            if [ -f "$cert" ] && [ -s "$cert" ]; then
              # Capture orapki output to check for specific errors
              if orapki_output=$(orapki wallet add -wallet ${{ env.WALLET_DIR }} -trusted_cert -cert "$cert" -auto_login_only 2>&1); then
                cert_count=$((cert_count + 1))
                # Show progress every 50 certificates
                if [ $((cert_count % 50)) -eq 0 ]; then
                  echo "Added $cert_count Mozilla certificates so far..."
                fi
              else
                if echo "$orapki_output" | grep -q "PKI-04003.*already present"; then
                  duplicate_count=$((duplicate_count + 1))
                else
                  failed_count=$((failed_count + 1))
                fi
              fi
            fi
          done
          echo "Successfully added $cert_count new Mozilla CA certificates"
          if [ $duplicate_count -gt 0 ]; then
            echo "Skipped $duplicate_count duplicate certificates"
          fi
          if [ $failed_count -gt 0 ]; then
            echo "Failed to add $failed_count certificates"
          fi
          rm mozilla-*.pem
          
          # Ensure we have at least some certificates (counting new + duplicates as success)
          total_processed=$((cert_count + duplicate_count))
          if [ $total_processed -eq 0 ]; then
            echo "ERROR: No Mozilla CA certificates were processed successfully"
            exit 1
          fi
          
      - name: Validate wallet contents
        run: |
          echo "Validating wallet contents..."
          if [ ! -f "${{ env.WALLET_DIR }}/cwallet.sso" ]; then
            echo "ERROR: cwallet.sso not found"
            echo "Wallet directory contents:"
            ls -la ${{ env.WALLET_DIR }}
            exit 1
          fi
          
          echo "Wallet files:"
          ls -la ${{ env.WALLET_DIR }}
          
          echo "Listing trusted certificates in wallet..."
          if wallet_display=$(orapki wallet display -wallet ${{ env.WALLET_DIR }} 2>&1); then
            echo "$wallet_display" | head -20
            
            # Count certificates
            cert_count=$(echo "$wallet_display" | grep -c "Trusted Certificate" || echo "0")
            echo "Total trusted certificates in wallet: $cert_count"
            
            if [ "$cert_count" -lt 50 ]; then
              echo "WARNING: Expected more certificates (found $cert_count)"
              echo "This may indicate certificate processing issues"
            elif [ "$cert_count" -lt 100 ]; then
              echo "INFO: Found $cert_count certificates (acceptable but below expected ~150+)"
            else
              echo "SUCCESS: Found $cert_count certificates"
            fi
          else
            echo "ERROR: Could not display wallet contents"
            echo "orapki wallet display output: $wallet_display"
            exit 1
          fi
          
      - name: Create wallet metadata
        run: |
          # Set proper permissions before creating metadata
          chmod 644 ${{ env.WALLET_DIR }}/*.sso ${{ env.WALLET_DIR }}/*.p12 2>/dev/null || true
          
          cat > ${{ env.WALLET_DIR }}/wallet-info.txt << EOF
          Oracle Wallet Build Information
          ===============================
          Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          Build ID: ${{ github.run_id }}
          Git SHA: ${{ github.sha }}
          
          Certificate Sources:
          - Amazon RDS Global Bundle
          - Amazon RDS Regional Bundles (us-east-1, us-west-2, eu-west-1)
          - Mozilla CA Bundle
          
          Total Certificates: $(orapki wallet display -wallet ${{ env.WALLET_DIR }} | grep -c "Trusted Certificate" || echo "0")
          
          Usage:
          Copy the contents of this directory to your Oracle client configuration.
          Update your sqlnet.ora file to point to the wallet location.
          
          Compatible with Oracle 12c and later versions.
          EOF
          
          chmod 644 ${{ env.WALLET_DIR }}/wallet-info.txt
          echo "Wallet metadata created:"
          cat ${{ env.WALLET_DIR }}/wallet-info.txt
          
      - name: Prepare wallet for upload
        run: |
          echo "Setting final permissions for wallet files..."
          # Use basic commands instead of find (which may not be available)
          chmod 644 ${{ env.WALLET_DIR }}/* 2>/dev/null || true
          chmod 755 ${{ env.WALLET_DIR }} 2>/dev/null || true
          
          # Alternative approach using ls and xargs if available
          if command -v ls >/dev/null 2>&1; then
            for file in ${{ env.WALLET_DIR }}/*; do
              if [ -f "$file" ]; then
                chmod 644 "$file" || true
              fi
            done
          fi
          
          echo "Final wallet contents:"
          ls -la ${{ env.WALLET_DIR }}
          
      - name: Upload wallet artifact
        uses: actions/upload-artifact@v4
        with:
          name: oracle-public-ca-wallet-${{ github.run_id }}
          path: ${{ env.WALLET_DIR }}
          retention-days: 90
          if-no-files-found: error
          
      - name: Upload wallet for release
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: oracle-public-ca-wallet-release
          path: ${{ env.WALLET_DIR }}
          retention-days: 365
